### ISSUE TITLE
please convert paper 1 and 2 to markdown 

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-704#1]
please convert paper 1 and 2 to markdown as we no longer accept latex 

you can use pandoc and leverage documentation in our epubs to help you with it

make sure yo create valid markdown. Our notation.md has instructions on how to do figures, tables, and bibliography

**Comment by zrmeier** [comment]
I have converted them to markddown via the conversion through pandoc, does it look appropriate? Or do I need to style it?

**Comment by laszewsk** [comment]
title missing, title can be only one with one #
convert underlins to #
see markdown

**Comment by zrmeier** [comment]
Okay I believe I have remedied this
