### ISSUE TITLE
where is project?

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-704#2]

**Comment by laszewsk** [comment]
- [x] convert project report to md
- [x] check md in into  hid-sp18-704/project-report you can use the Makefile from hid-sample to check your epub
- [x] check code in into  hid-sp18-704/project-code, there is no code in the old directory
- [x] if this is report only please indicate  
- [ ] original latex text has citations not properly placed in text, thus the report would be rejected if not fixed. we will only start review once its converted to md and citations are integrated. furthermore the report is a year old and i propose you check it for new developments or activities in taht area

**Comment by zrmeier** [comment]
I have update my project and it is now in my main directory under project-report which is report only, no code.
