### ISSUE TITLE
citations

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-704#3]
- [x] so your research shows that there is only a single citation for paper 1?
- [x] so your research shows that there is only a single citation for paper 2?

**Comment by zrmeier** [comment]
I have 4 citations for report 1, and 5 for report 2.

I have been trying to add references with pandoc, everytime i try to make it work for mark down it does now work.  I can get it to work in html but i know that is not an accepted format.

**Comment by laszewsk** [comment]
look at hid-sample there is a make file and metadata.txt you can use this to create the epub from md, citations will show up if you use pandoc

**Comment by laszewsk** [comment]
we have office hours every thursay evening

**Comment by zrmeier** [comment]
The Epub does indeed have the correct citations in there.  Is that sufficient?

**Comment by laszewsk** [comment]
```
we do not use @Electronic but @Misc 
this may be tehe reason for issues

labels should be in such a form that when we merge them with 180 other rports they are uniqe best is

<author><year><topic>
if a www resource we do 

www-<author><year><topic>
```

**Comment by zrmeier** [comment]
Okay I have Updated all @ Electronic to @ Misc and updated the bibtext keys to reflect the label format.
